[build]
  command = "vite build"
  publish = "dist"

[[redirects]]
  from = "/auth/*"
  to = "http://<YOUR-CORRECT-IP>:8000/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/user/*"
  to = "http://<YOUR-CORRECT-IP>:8000/user/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
